name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: Release Please

    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}

    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          config-file: .release-please/release-please-config.json
          manifest-file: .release-please/.release-please-manifest.json

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}

    steps:
      - name: Parse Version
        id: version
        run: echo "version=$(echo "${{ needs.release-please.outputs.tag_name }}" | cut -c 2-)" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} build/libs/AltairVelocity-*.jar
